services:
  web:
    build: .
    depends_on:
      - redis
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./
        target: /app
      - logvolume01:/var/log
    links:
      - redis
      - mongo
  redis:
    image: redis:7-alpine
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  mongo:
    image: mongo:5-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
volumes:
  logvolume01: {}
  mongodb: {}