import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import { useSession, signIn, signOut } from "next-auth/react"
import { getToken } from "next-auth/jwt"

// function Profile () {
//     const { data, error } = useSWR('https://api.opendota.com/api/live')
//
//     if (error) return <div>failed to load</div>
//     if (!data) return <div>loading...</div>
//
//     // render data
//     return <div>hello {data[0]["server_steam_id"]}!</div>
// }

function UserComp() {
    const { data: session } = useSession()

    if (session) {
        return (
            <>
                Signed in as {session.user.email} <br />
                <button onClick={() => signOut()}>Sign out</button>
            </>
        )
    }
    return (
        <>
            Not signed in <br />
            <button onClick={() => signIn('twitch')}>Sign in</button>
        </>
    )
}

export default function Home() {
    let dir = async () => {
        // const dirHandle = await window.showDirectoryPicker();
        // const promises = [];
        // let fileHandle;
        // let url;
        // for await (const entry of dirHandle.values()) {
        //     if (entry.kind !== 'file') {
        //         break;
        //     }
        //     promises.push(entry.getFile().then(async (file) => {
        //         console.log(file);
        //         url = URL.createObjectURL(fileHandle);
        //     }));
        // }
        // await Promise.all(promises);
        // const audio = new Audio(url);
        // audio.play().catch(console.log);
        let [fileHandle] = await window.showOpenFilePicker();
        let file = await fileHandle.getFile();
        const url = URL.createObjectURL(file);
        const audio = new Audio(url);
        audio.volume = 0.10;
        audio.play().catch(console.log);
        console.log(fileHandle);
    };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
            <button onClick={dir}>Escolher diretório</button>
            <UserComp/>
        </h1>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
